version: "3.9"
services:
  api:
    image: demo
    ports:
      - "8081:8080"
    depends_on:
      - database

  database:
    container_name: 'mysql'
    image: mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
